version: '3.8'
services:
  backend:
    build: .
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      # Spring Boot sẽ kết nối với Redis & RabbitMQ thông qua TÊN SERVICE trong Docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST_PROD}:5432/${POSTGRES_DB_PROD}?sslmode=require
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER_PROD}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD_PROD}

      - SPRING_DATA_REDIS_HOST=${REDIS_HOST_PROD}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT_PROD}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD_PROD}

      - SPRING_RABBITMQ_ADDRESSES=${CLOUDAMQP_URL}

      - SPRING_PROFILES_ACTIVE=prod

      - SENDGRID_API_KEY=${SENDGRID_API_KEY}

      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

      - JWT_SECRET=${JWT_SECRET}

      - GITHUB_CLIENT_ID_PROD=${GITHUB_CLIENT_ID_PROD}
      - GITHUB_CLIENT_SECRET_PROD=${GITHUB_CLIENT_SECRET_PROD}
    restart: unless-stopped