jwt_expire: 86400000
jwt_secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
logging:
    level:
        com:
            trung: DEBUG
        root: INFO
spring:
    application:
        name: Intership-Management-System
    data:
        redis:
            host: localhost
            password: 123456
            port: 6379
    rabbitmq:
        port: 5672
        host: localhost
        username: guest
        password: guest
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 123456
        url: jdbc:postgresql://localhost:5432/intership_management_system
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB

file:
    upload-dir: uploads

rabbitmq:
    exchange:
        name: intership_exchange
    queue:
        notification: notification_queue
    routing:
        key:
            notification: notification_routing_key