jwt_expire: 86400000
jwt_secret: YOUR_JWT_SECRET

logging:
  level:
    com:
      trung: DEBUG
    root: INFO

spring:
  application:
    name: Intership-Management-System

  data:
    redis:
      host: localhost
      port: 6379
      password: YOUR_REDIS_PASSWORD

  rabbitmq:
    host: localhost
    port: 5672
    username: YOUR_RABBITMQ_USERNAME
    password: YOUR_RABBITMQ_PASSWORD

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intership_management_system
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: uploads

rabbitmq:
  exchange:
    name: intership_exchange

  queue:
    notification: notification_queue

  routing:
    key:
      notification: notification_routing_key