logging:
  level:
    com:
      trung: DEBUG
    root: INFO
spring:
  data:
    redis:
      host: redis
      port: 6379
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: admin
    password: admin123
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://postgres:5432/intership_management_system
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.sendgrid.net
    port: 2525
    username: apikey
    password: "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"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbitmq:
  exchange:
    name: intership_exchange
  queue:
    notification: notification_queue
  routing:
    key:
      notification: notification_routing_key

