name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build and Test with Maven
        run: ./mvnw clean test

  deploy-to-render:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deployment
        run: |
          echo "CI thành công! Đang kích hoạt Render Deploy Hook..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          echo "Đã gửi tín hiệu thành công sang Render!"